# Generated by Django 2.2.16 on 2021-10-08 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='confirmation_code',
            field=models.CharField(blank=True, max_length=128, verbose_name='confirmation_code'),
        ),
    ]
