# Generated by Django 2.2.16 on 2021-10-08 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0008_auto_20211009_0007'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Genre_Title',
        ),
    ]
